### ISSUE TITLE
Does not compile on macOS sierra with Oracle Java 1.8

### ISSUE THREAD

**Issue by edigonzales** [claeis/iox-ili#5]
Find attached a patch.

[Btree.diff.zip](https://github.com/claeis/iox-ili/files/768439/Btree.diff.zip)

**Comment by edigonzales** [comment]
When using the generated jar (`ant jar`) with `ilivalidator`:

`Exception in thread "main" java.lang.NoClassDefFoundError: ch/ehi/iox/ilisite/ILIREPOSITORY09
	at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(RepositoryAccess.java:295)
	at ch.interlis.ilirepository.impl.RepositoryAccess.readIliModelsXml(RepositoryAccess.java:283)
	at ch.interlis.ilirepository.impl.RepositoryAccess.getIliFiles(RepositoryAccess.java:109)
	at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataShallow(RepositoryCrawler.java:178)
	at ch.interlis.ilirepository.impl.RepositoryCrawler.getIliFileMetadataDeep(RepositoryCrawler.java:100)
	at ch.interlis.ilirepository.IliManager.createConfig(IliManager.java:335)
	at ch.interlis.ilirepository.IliManager.getConfig(IliManager.java:298)
	at org.interlis2.validator.Validator.compileIli(Unknown Source)
	at org.interlis2.validator.Validator.runValidation(Unknown Source)
	at org.interlis2.validator.Main.main(Unknown Source)
Caused by: java.lang.ClassNotFoundException: ch.ehi.iox.ilisite.ILIREPOSITORY09
	at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:331)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 10 more`

I added `./src/main/gen-java` directory in ant's `compile` task. Something like `<src path="${gen-java}" />`
